# Test against this version of node
environment:
  matrix:
    - nodejs_version: "6"

# Install scripts (run after repo cloning)
install:
  - ps: "Install-Product node $env:nodejs_version"
  - npm install

# Post install scripts
test_script:
  - node --version
  - npm --version
  - npm run test
  